theme = "catppuccin_mocha"

[editor]
cursorline = true
scrolloff = 8
bufferline = "multiple"
idle-timeout = 0
rulers = [100]
true-color = true
completion-replace = true
trim-trailing-whitespace = true
insert-final-newline = true
auto-pairs = true
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.smart-tab]
enable = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
right = ["diagnostics", "position", "file-encoding"]

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"

[editor.indent-guides]
render = true
character = "│"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true
inlay-hints-length-limit = 15

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-space = "goto_word"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

[keys.insert]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-space = "goto_word"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
"C-." = "completion"
j = { k = "normal_mode" }

[keys.select]
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-space = "goto_word"
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
